spring.application.name=gerenciamento-alunos
server.port: 8080

spring.datasource.url:jdbc:postgresql://localhost:5432/test
spring.datasource.username:postgres
spring.datasource.password:postgresql

spring.jpa.hibernate.ddl-auto:update
